// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aomdycgbmfwccezxijmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbWR5Y2dibWZ3Y2Nlenhpam1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMzkxMzIsImV4cCI6MjA1NTYxNTEzMn0.gUhgLc6se0l9Bu5nrDeRD2avuzYYlGeuDzNzULP6-yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);